In [1]:
import pandas as pd
cars = pd.read_csv(r"C:/Users/DELL/Documents/GitHub/IH_DA_FT_MAR_2023/Class_Materials/Pandas/Labs/vehicles.csv")
# print(cars)

In [2]:
cars.head()

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950
1,AM General,FJ8c Post Office,1984,4.2,6,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
4,ASC Incorporated,GNX,1987,3.8,6,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550

In [31]:
#print(cars["Model"].count())
print(cars["Model"].nunique())

3608

In [59]:
df1= cars.groupby("Make").count()
display(df1.columns)

Index(['Model', 'Year', 'Engine Displacement', 'Cylinders', 'Transmission',
       'Drivetrain', 'Vehicle Class', 'Fuel Type', 'Fuel Barrels/Year',
       'City MPG', 'Highway MPG', 'Combined MPG', 'CO2 Emission Grams/Mile',
       'Fuel Cost/Year'],
      dtype='object')

In [87]:
sdf=cars.groupby(['Make'], as_index=False).count()
df2 = pd.DataFrame(sdf)
display(df2)

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
0,AM General,4,4,4,4,4,4,4,4,4,4,4,4,4,4
1,ASC Incorporated,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2,Acura,302,302,302,302,302,302,302,302,302,302,302,302,302,302
3,Alfa Romeo,41,41,41,41,41,41,41,41,41,41,41,41,41,41
4,American Motors Corporation,22,22,22,22,22,22,22,22,22,22,22,22,22,22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122,Volkswagen,1047,1047,1047,1047,1047,1047,1047,1047,1047,1047,1047,1047,1047,1047
123,Volvo,717,717,717,717,717,717,717,717,717,717,717,717,717,717
124,Wallace Environmental,32,32,32,32,32,32,32,32,32,32,32,32,32,32
125,Yugo,8,8,8,8,8,8,8,8,8,8,8,8,8,8
126,smart,20,20,20,20,20,20,20,20,20,20,20,20,20,20

In [91]:
df3= df2.query('Model==Model.max()')
display(df3.columns)

Index(['Make', 'Model', 'Year', 'Engine Displacement', 'Cylinders',
       'Transmission', 'Drivetrain', 'Vehicle Class', 'Fuel Type',
       'Fuel Barrels/Year', 'City MPG', 'Highway MPG', 'Combined MPG',
       'CO2 Emission Grams/Mile', 'Fuel Cost/Year'],
      dtype='object')

In [9]:
df4= cars.groupby(['Make'], as_index=False)['CO2 Emission Grams/Mile'].mean()
display(df4)

                            Make  CO2 Emission Grams/Mile
0                     AM General               611.358244
1               ASC Incorporated               555.437500
2                          Acura               422.585325
3                     Alfa Romeo               463.952115
4    American Motors Corporation               505.758823
..                           ...                      ...
122                   Volkswagen               392.741721
123                        Volvo               435.803755
124        Wallace Environmental               657.990029
125                         Yugo               356.068256
126                        smart               247.030556

[127 rows x 2 columns]

In [10]:
df5= df4.sort_values('CO2 Emission Grams/Mile')
display(df5)

                                   Make  CO2 Emission Grams/Mile
36                               Fisker               169.000000
126                               smart               247.030556
35                                 Fiat               304.666560
26                             Daihatsu               310.188060
67                                 MINI               313.716862
..                                  ...                      ...
58               Laforza Automobile Inc               807.909091
15                              Bugatti               873.062500
112    Superior Coaches Div E.p. Dutton               888.700000
101  S and S Coach Company  E.p. Dutton               888.700000
119                              Vector              1049.159722

[127 rows x 2 columns]

In [4]:
cars['Year'].describe()

count    35952.00000
mean      2000.71640
std         10.08529
min       1984.00000
25%       1991.00000
50%       2001.00000
75%       2010.00000
max       2017.00000
Name: Year, dtype: float64

#(Optional)
#Use pd.cut or pd.qcut to create 4 groups (bins) of cars, by Year. 
#We want to explore how cars have evolved decade by decade.

In [97]:
cars['Year'].unique()

array([1984, 1985, 1987, 1997, 1998, 1999, 1995, 1996, 2001, 2002, 2003,
       2000, 2004, 2013, 2014, 2015, 2016, 2017, 1986, 1988, 1989, 1990,
       1991, 1992, 1993, 1994, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
       2012], dtype=int64)

In [100]:
cars.sort_values(by=['Year'], inplace=True)

In [101]:
cars['Year'].unique()

array([1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994,
       1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005,
       2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016,
       2017], dtype=int64)

In [93]:
(2017-1984)/4

8.25

In [65]:
cars.groupby(['Year']).filter(lambda x: x["Year"].mean().sort_values(by="Year"))

AttributeError: 'float' object has no attribute 'sort_values'

In [83]:
import pandas as pd
import numpy as np
cars = pd.cut(np.array ('bins'[0,4,8,10], 4))

<>:3: SyntaxWarning: str indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:3: SyntaxWarning: str indices must be integers or slices, not tuple; perhaps you missed a comma?
C:\Users\DELL\AppData\Local\Temp\ipykernel_5104\835517264.py:3: SyntaxWarning: str indices must be integers or slices, not tuple; perhaps you missed a comma?
  cars = pd.cut(np.array ('bins'[0,4,8,10], 4))

TypeError: string indices must be integers

In [39]:
df5 = pd.cut('Year',['Year'].labels=False, retbins=True,
       right=False, duplicates='drop')

SyntaxError: expression cannot contain assignment, perhaps you meant "=="? (2165442869.py, line 1)

In [30]:
bins = [0, 4, 6, 10]
Years = ["1985","2005","2015","2017"]
df5['Years'] = pd.cut(df5['Years'], bins=bins, labels=labels)

KeyError: 'Years'

In [ ]:
#Did cars consume more gas in the eighties?
#show the average City_Km/Liter by year_range

In [ ]:
#Which brands are more environment friendly?#

In [92]:
df= cars.groupby(['Year'], as_index=False).loc['Year'].mean()
display(df)

AttributeError: 'DataFrameGroupBy' object has no attribute 'loc'

In [5]:
cars.groupby('Year').agg(['max',"min"])

                       Make                               Model  \
                        max               min               max
Year
1984             Volkswagen        AM General         Wagon 4WD
1985                  Volvo        AM General             XT-DL
1986                   Yugo             Acura             XT-DL
1987                   Yugo  ASC Incorporated             XT-DL
1988                   Yugo             Acura             XT-DL
1989                   Yugo             Acura             XT-DL
1990                   Yugo             Acura            XT 4WD
1991  Wallace Environmental             Acura            XT 4WD
1992  Wallace Environmental             Acura    Yukon 1500 4WD
1993                  Volvo             Acura    Yukon 1500 4WD
1994                  Volvo             Acura   Yukon K1500 4WD
1995                  Volvo             Acura    Yukon 1500 4WD
1996                  Volvo             Acura       Z3 Roadster
1997                  Volvo             Acura       Z3 Roadster
1998                  Volvo             Acura       Z3 Roadster
1999                  Volvo             Acura       Z3 Roadster
2000                  Volvo             Acura                Z8
2001                  Volvo             Acura                Z8
2002                  Volvo             Acura                Z8
2003                  Volvo             Acura                Z8
2004                  Volvo             Acura                xB
2005                  Volvo             Acura                xB
2006                  Volvo             Acura                xB
2007                  Volvo             Acura                tC
2008                  smart             Acura                xD
2009                  smart             Acura                xD
2010                  smart             Acura                xD
2011                  smart             Acura                xD
2012                  smart             Acura                xD
2013                  smart             Acura                xD
2014                  smart             Acura                xD
2015                  smart             Acura                xB
2016                  smart             Acura                tC
2017                  smart             Acura  fortwo cabriolet

                        Engine Displacement      Cylinders      Transmission  \
                    min                 max  min       max min           max
Year
1984           1fas 410                 6.2  1.0         8   4  Manual 5-spd
1985    1-Ton Truck 2WD                 6.8  1.0        12   2  Manual 5-spd
1986    1-Ton Truck 2WD                 6.8  1.0        12   2  Manual 5-spd
1987    1-Ton Truck 2WD                 6.8  1.0        12   2  Manual 5-spd
1988    1-Ton Truck 2WD                 6.8  1.0        12   2  Manual 5-spd
1989    1-Ton Truck 2WD                 6.8  1.0        12   2  Manual 6-spd
1990    1-Ton Truck 2WD                 7.4  1.0        12   2  Manual 6-spd
1991    1-Ton Truck 2WD                 7.4  1.0        12   2  Manual 6-spd
1992    1-Ton Truck 2WD                 8.0  1.0        12   2  Manual 6-spd
1993                100                 8.0  1.0        12   2  Manual 6-spd
1994                100                 8.0  1.0        12   2  Manual 6-spd
1995                164                 8.0  1.0        12   2  Manual 6-spd
1996        2.5TL/3.2TL                 8.0  1.0        12   3  Manual 6-spd
1997        2.2CL/3.0CL                 6.8  1.0        12   3  Manual 6-spd
1998        2.3CL/3.0CL                 8.0  1.0        12   3  Manual 6-spd
1999        2.3CL/3.0CL                 8.0  1.0        12   3  Manual 6-spd
2000           2500 2WD                 8.0  1.0        12   3  Manual 6-spd
2001              3-Sep                 8.0  1.0        12   3  Manual 6-spd
2002              3-Sep                 8.0  1.0        12   3  Manual 6-spd
2003              3.2CL                 8.3  1.0        12   3  Manual 6-spd
2004                  3                 8.3  1.0        12   2  Manual 6-spd
2005                  3                 8.3  1.0        12   2  Manual 6-spd
2006                  3                 8.3  1.0        16   2  Manual 6-spd
2007                  3                 7.0  1.3        12   2  Manual 6-spd
2008               128i                 8.4  1.0        16   2  Manual 6-spd
2009               128i                 8.4  1.0        12   2  Manual 6-spd
2010  128ci Convertible                 8.4  1.0        16   2  Manual 7-spd
2011  128ci Convertible                 8.0  1.0        16   2  Manual 6-spd
2012  128ci Convertible                 8.0  1.0        16   3  Manual 7-spd
2013  128ci Convertible                 8.4  1.0        16   3  Manual 7-spd
2014           1500 2WD                 8.4  0.6        16   2  Manual 7-spd
2015           1500 2WD                 8.4  0.6        16   2  Manual 7-spd
2016           1500 2WD                 8.4  0.6        12   2    Manual(M7)
2017         124 Spider                 8.4  0.9        12   3    Manual(M7)

                                        ... City MPG     Highway MPG      \
                                   min  ...      max min         max min
Year                                    ...
1984                   Automatic 3-spd  ...       31   8          35  10
1985                   Automatic 3-spd  ...       40   7          48   9
1986                    Automatic (S4)  ...       44   6          53   9
1987                   Automatic 3-spd  ...       44   6          51   9
1988                   Automatic 3-spd  ...       44   6          51  10
1989  Automatic (variable gear ratios)  ...       43   6          52  10
1990                    Automatic (S4)  ...       43   6          52  10
1991                    Automatic (S4)  ...       43   8          52  10
1992                    Automatic (S4)  ...       43   7          52  10
1993                    Automatic (S4)  ...       43   7          52  10
1994                    Automatic (S5)  ...       43   9          52  13
1995                   Automatic 3-spd  ...       39   7          50  10
1996  Automatic (variable gear ratios)  ...       37   7          44  12
1997                          Auto(L3)  ...       37   8          44  12
1998  Automatic (variable gear ratios)  ...       36   8          45  13
1999  Automatic (variable gear ratios)  ...       35   8          44  13
2000                    Automatic (S6)  ...       49   8          61  12
2001                    Automatic (S4)  ...       48   8          60  12
2002                    Automatic (S4)  ...       48   8          59  12
2003                    Automatic (S4)  ...       48   7          59  11
2004                    Automatic (S4)  ...       48   8          58  11
2005                    Automatic (S4)  ...       48   8          58  11
2006                    Automatic (S4)  ...       48   8          58  11
2007                    Automatic (S4)  ...       48   8          45  13
2008                    Automatic (S4)  ...       48   8          45  13
2009                         Auto(AM7)  ...       48   8          45  13
2010                      Auto (AV-S6)  ...       51   8          48  13
2011                         Auto (AV)  ...       51   8          48  13
2012                         Auto (AV)  ...       53   8          49  13
2013                       Auto(AM-S6)  ...       53   8          49  13
2014                          Auto(A1)  ...       53   8          49  12
2015                       Auto(AM-S6)  ...       53   8          49  14
2016                       Auto(AM-S6)  ...       58  10          53  13
2017                       Auto(AM-S6)  ...       58  10          53  15

     Combined MPG     CO2 Emission Grams/Mile             Fuel Cost/Year
              max min                     max         min            max   min
Year
1984           31   9              987.444444  328.387097           3700  1150
1985           43   8             1110.875000  206.674419           4150   750
1986           48   7             1269.571429  185.145833           5800   700
1987           47   7             1269.571429  189.085106           5800   700
1988           47   7             1269.571429  189.085106           5800   700
1989           47   7             1269.571429  189.085106           5800   700
1990           47   7             1269.571429  189.085106           5800   700
1991           47  10              888.700000  189.085106           4050   700
1992           47   8             1110.875000  189.085106           5050   700
1993           47   8             1110.875000  189.085106           5050   700
1994           47  10              888.700000  189.085106           4050   700
1995           43   8             1110.875000  206.674419           5050   750
1996           40   9              987.444444  222.175000           4500   850
1997           40   9              987.444444  222.175000           4500   850
1998           40  10              888.700000  222.175000           4050   850
1999           38  10              888.700000  240.189189           4050   900
2000           53   9              987.444444  167.679245           4500   650
2001           53   9              987.444444  167.679245           4500   650
2002           53  10              888.700000  167.679245           4050   650
2003           53   8             1110.875000  167.679245           5050   650
2004           52  10              888.700000  170.903846           4050   650
2005           52   9              987.444444  170.903846           4500   650
2006           52   9              987.444444  170.903846           4500   650
2007           46  10              888.700000  193.195652           4050   700
2008           46  10              888.700000  193.195652           4050   700
2009           46  10              888.700000  193.195652           4050   700
2010           50  10              888.700000  177.740000           4050   650
2011           50  10              888.700000   84.000000           4050   650
2012           50  10              888.700000   87.000000           4050   650
2013           50  10              847.000000   81.000000           4050   650
2014           50  10              847.000000   40.000000           4050   650
2015           50  10              847.000000   40.000000           4050   650
2016           56  12              762.000000   37.000000           3400   600
2017           56  12              724.000000   51.000000           3400   600

[34 rows x 28 columns]